version: '3'

services:
  departures-time-api:
    container_name: departures-time-api
    build:
      context: ./departures-time-api
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    command: sleep infinity
    working_dir: /go/src/work
    volumes:
      - ./departures-time-api:/go/src/work
    tty: true
    environment:
      - NEA_REST_API_PATH=https://station.ic731.net/api/nearest
      - EKISPERT_API_PATH=http://api.ekispert.jp/v1/json/
      - EKISPERT_API_KEY=<your api key>
