/* tslint:disable */
/* eslint-disable */
/**
 * departures-time
 * 現在地から最寄駅を取得し、目的地駅を名前から決めて経路検索を行うAPI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: iioka.takumi.quena@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api';
export * from './configuration';
